name: bandung_sewa_motor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  get: 4.6.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  skeletonizer: ^1.3.0
  widget_zoom: ^0.0.4

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
